[package]
name = "ira"
version = "0.1.0"
authors = ["vladimir.lopez"]
license = "MIT"
edition = "2021"

[dependencies]
ratatui = "0.27.0"
winapi = { version = "0.3.9", features = [
    "fileapi",
    "winbase",
    "errhandlingapi",
    "handleapi",
] }
