[package]
name = "ira"
version = "0.1.0"
authors = ["vladimir.lopez"]
license = "MIT"
edition = "2021"

[dependencies]
dirs-next = "2.0.0"
open = "5.4.3"
parking_lot = "0.12.5"
ratatui = "0.30.2"
winapi = { version = "0.3.9", features = [
    "fileapi",
    "winbase",
    "errhandlingapi",
    "handleapi",
] }
