[package]
name = "ira"
version = "0.1.0"
description = "A terminal file manager built with Ratatui and crossterm"
repository = "https://github.com/drivesensei/ira"
authors = ["vladimir.lopez"]
license = "MIT"
edition = "2021"
keywords = ["tui", "file-manager", "terminal"]
categories = ["command-line-utilities"]

[dependencies]
dirs-next = "2.0.0"
open = "5.4.3"
parking_lot = "0.12.5"
ratatui = "0.30.2"
winapi = { version = "0.3.9", features = [
    "fileapi",
    "winbase",
    "errhandlingapi",
    "handleapi",
] }
