name: Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggering the workflow on tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Cache Cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry
          restore-keys: |
            ${{ runner.os }}-cargo-registry

      - name: Cache Cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/index
          key: ${{ runner.os }}-cargo-index
          restore-keys: |
            ${{ runner.os }}-cargo-index

      - name: Cache Cargo build
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build
          restore-keys: |
            ${{ runner.os }}-cargo-build

      - name: Build
        run: cargo build --release

      - name: Archive binaries
        if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest'
        run: tar -czf ${GITHUB_RUN_NUMBER}_ira_${matrix.platform}.tar.gz -C target/release ira

      - name: Archive binary (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          Compress-Archive -Path target\release\ira.exe -DestinationPath ${GITHUB_RUN_NUMBER}_ira_windows.zip

      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: ira-${{ matrix.platform }}
          path: |
            ${GITHUB_RUN_NUMBER}_ira_${{ matrix.platform }}.tar.gz
            ${GITHUB_RUN_NUMBER}_ira_windows.zip

  create_release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tar.gz
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
