name: Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggering the workflow on tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Cache Cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry
          restore-keys: |
            ${{ runner.os }}-cargo-registry

      - name: Cache Cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/index
          key: ${{ runner.os }}-cargo-index
          restore-keys: |
            ${{ runner.os }}-cargo-index

      - name: Cache Cargo build
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build
          restore-keys: |
            ${{ runner.os }}-cargo-build

      - name: Build
        run: cargo build --release

      - name: Archive binaries (Linux/macOS)
        if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest'
        env:
          FILENAME: ira-${{ matrix.platform }}-${{ github.run_number }}.tar.gz
        run: tar -czf $FILENAME -C target/release ira

      - name: Archive binary (Windows)
        if: matrix.platform == 'windows-latest'
        env:
          FILENAME: ira-windows-${{ github.run_number }}.zip
        run: |
          Compress-Archive -Path target\release\ira.exe -DestinationPath $env:FILENAME

      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: ira-${{ matrix.platform }}
          path: ${{ env.FILENAME }}

  create_release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tar.gz
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
