[package]
name = "ira-desktop"
version = "0.1.0"
edition = "2024"
publish = false

[target.'cfg(target_os = "linux")'.dependencies]
gpui = { version = "0.2.2", default-features = false, features = ["font-kit", "wayland", "x11"] }

[target.'cfg(target_os = "macos")'.dependencies]
gpui = { version = "0.2.2", default-features = false, features = ["font-kit"] }

[target.'cfg(target_os = "windows")'.dependencies]
gpui = { version = "0.2.2", default-features = false }
